services:
  nomenclatura-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nomenclatura-app
    ports:
      - "8003:80"
    volumes:
      - /home/rootadmin/data/nomenclatura:/home/rootadmin/data/nomenclatura
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
